[tox]
minversion = 3.0
skipsdist = true
envlist = py3

[testenv]
deps =
    -r tox-requirements.txt
passenv = *
setenv =
    ANSIBLE_HOST_KEY_CHECKING = false
    MOLECULE_DRIVER = docker
    MOLECULE_VERIFIER = ansible

[testenv:py3]
changedir = {toxinidir}
commands =
    molecule test --scenario-name default

[testenv:podman]
setenv =
    MOLECULE_DRIVER = podman
commands =
    molecule test --scenario-name podman
